#!/bin/bash
# # Reference: https://github.com/dunst-project/dunst

is_installed() {
    package=$1
    cmd=$((dpkg -l $package | grep $package | cut -d " " -f1) 2>&1)
    if [[ $cmd = "ii" ]]; then
        res=1
    else
        res=0
    fi
}

# Combine all the build dependencies into an array
packages=(dunst i3lock eww)
tmp=()
for pkg in ${packages[@]}; do
    tmp+=($(bash "$pkg"_config prerequisites))
done

# Remove duplicates
declare -A dependencies
for dep in ${tmp[@]}; do
    dependencies[$dep]=1
done

# Install any dependencies that aren't already installed
echo "======================= Installing prerequisites... ======================="
installed=()
icmd="sudo apt install -y"
for dep in ${!dependencies[@]}; do
    is_installed $dep
    if [[ $res = 0 ]]; then
	    echo "Installing $dep..."
        icmd="${icmd} ${dep}"
        installed+=($dep)
    fi
done

# Build the packages
echo "======================= Building packages... ======================="
for pkg in ${packages[@]}; do
    echo "Building $pkg..."
    bash "$pkg"_config build
done

# Remove dependencies that were not installed before
echo "======================= Removing prerequisites... ======================="
for dep in ${installed[@]}; do
    echo "Removing $dep..."
    sudo apt remove --purge -y $dep
done
sudo apt autoremove -y
