#!/bin/bash
# Build instructions: https://github.com/dunst-project/dunst#building

prerequisites() {
    echo "git make pkg-config libnotify-dev libxss-dev libglib2.0-dev libgdk-pixbuf2.0-dev libxinerama-dev libxrandr-dev librust-pangocairo-dev"
}

build() {
    git clone https://github.com/dunst-project/dunst.git
    cd dunst/
    make WAYLAND=0
    sudo make install WAYLAND=0
    cd ../
    rm -vrf dunst/
}

"$@"