#!/bin/bash

read -p "Chromium will open after you press enter. Once opened, please navigate to chrome://flags/#extension-mime-request-handling and change it to 'Always prompt for install'" tmp
flatpak run com.github.Eloston.UngoogledChromium
read -p "Press enter once you have updated this flag" tmp
flatpak run com.github.Eloston.UngoogledChromium "file://$(pwd)/chrome-extensions/Chromium.Web.Store.crx"
flatpak run com.github.Eloston.UngoogledChromium "file://$(pwd)/chrome-extensions/ublock.crx"
flatpak run com.github.Eloston.UngoogledChromium "file://$(pwd)/chrome-extensions/auto-history-wipe.crx"
flatpak run com.github.Eloston.UngoogledChromium "file://$(pwd)/chrome-extensions/canvas-fingerprint-defender.crx"
flatpak run com.github.Eloston.UngoogledChromium "file://$(pwd)/chrome-extensions/privacy-badger.crx"