# https://opensource.com/article/18/3/manage-workstation-ansible
# ansible-pull -e "ansible_become_password=[SUDO_PASSWORD]" -U https://github.com/chathura2031/ansible-test.git
- name: Install packages
  hosts: localhost
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Install udisks2 (provides udisksctl)
      apt:
        name: udisks2
        state: latest

    - name: Install vim (text editor)
      apt:
        name: vim
        state: latest

    - name: Install xorg (display server)
      apt:
        name: xorg
        state: latest

    - name: Install openbox (window manager)
      apt:
        name: openbox
        state: latest

    - name: Install obconf (openbox configuration utility)
      apt:
        name: obconf
        state: latest

    - name: Install lxappearance (theme switcher)
      apt:
        name: lxappearance
        state: latest

    - name: Install tint2 (panel manager)
      apt:
        name: tint2
        state: latest

    - name: Install xcompmgr (compositor)
      apt:
        name: xcompmgr
        state: latest

    - name: Install nitrogen (desktop background browser/setter)
      apt:
        name: nitrogen
        state: latest

    - name: Install alsa-base (API for sound card device drivers)
      apt:
        name: alsa-base
        state: latest

    - name: Install pavucontrol (volume control tool)
      apt:
        name: pavucontrol
        state: latest

          #     - name: Install libnotify (notification library)
          #       apt:
          #         name: libnotify
          #         state: latest

    - name: Install dunst (notification daemon/server)
      apt:
        name: dunst
        state: latest

    - name: Install xbacklight (brightness controller)
      apt:
        name: xbacklight
        state: latest

    - name: Install git
      apt:
        name: git
        state: latest

    - name: Install xclip
      apt:
        name: xclip
        state: latest

    - name: Install zip
      apt:
        name: zip
        state: latest

    - name: Install unzip
      apt:
        name: unzip
        state: latest

    - name: Install yakuake (terminal emulator)
      apt:
        name: yakuake
        state: latest

    - name: Install thunar (file manager)
      apt:
        name: thunar
        state: latest

    - name: Install jgmenu (app menu)
      apt:
        name: jgmenu
        state: latest

    - name: Add repository for ulauncher
      apt_repository:
        repo: ppa:agornostal/ulauncher

    - name: Install ulauncher (app launcher)
      apt:
        name: ulauncher
        state: latest

    - name: Install arc theme
      apt:
        name: arc-theme
        state: latest

    - name: Install flatpak (cross-distro package manager)
      apt:
        name: flatpak
        state: latest

    - name: Add flathub repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Install chromium (browser)
      flatpak:
        name: com.github.Eloston.UngoogledChromium
        state: present

    - name: Download vscode package
      get_url:
        url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
        dest: /tmp/code.deb

    - name: Install vscode
      apt:
        deb: /tmp/code.deb

    - name: Install mpv (video player)
      apt:
        name: mpv
        state: latest

    - name: Install qalculate
      apt:
        name: qalculate-gtk
        state: latest

    - name: Install thunderbird
      apt:
        name: thunderbird
        state: latest

    - name: Install libreoffice
      apt:
        name: libreoffice
        state: latest

    - name: Install discord
      flatpak:
        name: com.discordapp.Discord
        state: present

    - name: Install gimp
      apt:
        name: gimp
        state: latest

    - name: Install podman
      apt:
        name: podman
        state: latest

- name: Configure packages
  hosts: localhost
  tasks:
    - name: Set the timezone
      become: true
      community.general.timezone:
        name: Australia/Melbourne

    - name: Configure openbox
      become: true
      copy:
        src: ./openbox
        dest: /etc/xdg/

    - name: Configure xbacklight
      become: true
      copy:
        src: ./xorg.conf
        dest: /etc/X11/

    - name: Configure vim
      become: true
      copy:
        src: ./vimrc
        dest: /etc/vim/

    - name: Configure tint2
      copy:
        src: ./tint2rc
        dest: ~/.config/tint2/

    - name: Configure jgmenu
      copy:
        src: ./jgmenurc
        dest: ~/.config/jgmenu/

    - name: Configure ulauncher
      copy:
        src: ./ulauncher
        dest: ~/.config/

    - name: Transfer wallpapers
      copy:
        src: ./Wallpapers
        dest: ~/

    - name: Configure nitrogen
      copy:
        src: ./nitrogen
        dest: ~/.config/

    - name: Configure chromium
      copy:
        src: ./Preferences
        dest: ~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium/Default/

    - name: Configure start menu
      become: true
      copy:
        src: ./start_menu
        dest: /usr/bin/
        mode: preserve

    - name: Configure vscode
      copy:
        src: ./settings.json
        dest: ~/.config/Code/User/settings.json

    - name: Install vim in vscode
      shell:
        cmd: code --install-extension vscodevim.vim

# TODO: Add `flatpak run com.github.Eloston.UngoogledChromium Chromium.Web.Store.crx`
# TODO: Add dunstrc to /etc/xdg/dunst/dunstrc
# TODO: Install dunst from file until version is updated
# TODO: Make dunst by running `make WAYLAND=0 && sudo make install WAYLAND=0` and install `make pkg-config libnotify-dev libxss-dev libglib2.0-dev libgdk-pixbuf2.0-dev libpangocairo-1.0-0 libxinerama-dev libxrandr-dev`