# https://opensource.com/article/18/3/manage-workstation-ansible
# ansible-pull -e "ansible_become_password=[SUDO_PASSWORD]" -U https://github.com/chathura2031/ansible-test.git
- name: Install packages
  hosts: localhost
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Install udisks2 (provides udisksctl)
      apt:
        name: udisks2
        state: latest

    - name: Install vim (text editor)
      apt:
        name: vim
        state: latest

    - name: Install xorg (display server)
      apt:
        name: xorg
        state: latest

    - name: Install openbox (window manager)
      apt:
        name: openbox
        state: latest

    - name: Install obconf (openbox configuration utility)
      apt:
        name: obconf
        state: latest

    - name: Install tint2 (panel manager)
      apt:
        name: tint2
        state: latest

    - name: Install xcompmgr (compositor)
      apt:
        name: xcompmgr
        state: latest

    - name: Install nitrogen (desktop background browser/setter)
      apt:
        name: nitrogen
        state: latest

    - name: Install alsa-base (API for sound card device drivers)
      apt:
        name: alsa-base
        state: latest

    - name: Install pavucontrol (volume control tool)
      apt:
        name: pavucontrol
        state: latest

    - name: Install libnotify (notification library)
      apt:
        name: libnotify
        state: latest

    - name: Install dunst (notification daemon/server)
      apt:
        name: dunst
        state: latest

    - name: Install xbacklight (brightness controller)
      apt:
        name: xbacklight
        state: latest

    - name: Install git
      apt:
        name: git
        state: latest

    - name: Install xclip
      apt:
        name: xclip
        state: latest

    - name: Install zip
      apt:
        name: zip
        state: latest

    - name: Install unzip
      apt:
        name: unzip
        state: latest

    - name: Install yakuake (terminal emulator)
      apt:
        name: yakuake
        state: latest

    - name: Install thunar (file manager)
      apt:
        name: thunar
        state: latest

    - name: Install jgmenu (application launcher)
      apt:
        name: jgmenu
        state: latest

    - name: Install flatpak (cross-distro package manager)
      apt:
        name: flatpak
        state: latest

    - name: Add flathub repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Install chromium (browser)
      flatpak:
        name: com.github.Eloston.UngoogledChromium
        state: present

    - name: Install mpv (video player)
      apt:
        name: mpv
        state: latest

    - name: Install qalculate
      apt:
        name: qalculate-gtk
        state: latest

    - name: Install thunderbird
      apt:
        name: thunderbird
        state: latest

    - name: Install libreoffice
      apt:
        name: libreoffice
        state: latest

    - name: Install discord
      apt:
        name: discord
        state: latest

    - name: Install gimp
      apt:
        name: gimp
        state: latest

    - name: Install podman
      apt:
        name: podman
        state: latest

- name: Configure packages
  hosts: localhost
  tasks:
    - name: Set the timezone
      community.general.timezone:
        name: Australia/Melbourne

    - name: Setup openbox
      become: true
      copy:
        src: ./openbox
        dest: /etc/xdg/

    - name: Setup xbacklight
      become: true
      copy:
        src: ./xorg.conf
        dest: /etc/X11/

    - name: Setup vim
      become: true
      copy:
        src: ./vimrc
        dest: /etc/vim/

    - name: Setup tint2
      copy:
        src: ./tint2rc
        dest: ~/.config/tint2/

    - name: Setup start menu
      become: true
      copy:
        src: ./start_menu
        dest: /usr/bin/
        mode: preserve

