#!/bin/sh
fg_color=cdd6f400
wrong_color=ff0000aa
highlight_color=ffffffff
verif_color=333663ff
date_hour_color=ffffffff

slowfade () {
    dis=$(echo -n "$DISPLAY" | tr -c '[:alnum:]' _)
    ifc='com.github.chjj.compton'
    obj='/com/github/chjj/compton'
    if [[ "$1" == "start" ]]; then
        dbus-send --print-reply --dest=$ifc.$dis \
            $obj $ifc.opts_set string:fade_in_step double:0.02
        dbus-send --print-reply --dest=$ifc.$dis \
            $obj $ifc.opts_set string:fade_out_step double:0.02
    else
        dbus-send --print-reply --dest=$ifc.$dis \
            $obj $ifc.opts_set string:fade_in_step double:0.1
        dbus-send --print-reply --dest=$ifc.$dis \
            $obj $ifc.opts_set string:fade_out_step double:0.1
    fi
}

#playerctl -a pause
# $HOME/.scripts/cycle-dim &
# pkill -u "$USER" -USR1 dunst
# $HOME/.scripts/wait-suspend &
# sleep 1 && eww -c $HOME/.config/eww/Lock/ open-many player-spotify lock-weather battery-lock volume-slider-lock &
# sleep 0.09 && $HOME/eww/target/release/eww open lockscreen &
# eww -c $HOME/.config/eww/Powermenu close-all &
# slowfade start
i3lock -p default -n --force-clock -i ~/Wallpapers/Wallpaper_1920x1080.png \
--ind-pos="w/2:h/2" --time-pos="w/2:h/4" --date-pos="w/2:h/4-130" --greeter-pos="w/2:h/2" \
--insidever-color=62688000 --insidewrong-color=ffffff00 --inside-color=b3b9b800 \
--ringver-color=$verif_color --ringwrong-color=$wrong_color --ring-color=$fg_color \
--keyhl-color=$highlight_color --bshl-color=$highlight_color --separator-color=dadada00 \
--date-color=$date_hour_color --time-color=$date_hour_color --greeter-color=$fg_color  \
--time-str="%H:%M" --time-size=150 \
--date-str="%A %d %B %Y" --date-size=25 \
--greeter-text="" --greeter-size=25 \
--line-uses-inside --radius 106 --ring-width 4 --indicator \
--verif-text=""  --wrong-text="" --noinput-text="" \
--clock --date-font="Proxima Nova Bold" --time-font="Proxima Nova" \
--pass-media-keys
# slowfade end
# $HOME/eww/target/release/eww close lockscreen
