#!/bin/bash

ICONS_PATH="/home/chathura/ansible-test/volume-control/"
ICON_VOL0=$ICONS_PATH"vol0.png"
ICON_VOL1=$ICONS_PATH"vol1.png"
ICON_VOL2=$ICONS_PATH"vol2.png"
ICON_VOL3=$ICONS_PATH"vol3.png"

# Get the active device (ie. `Speaker` or `Headphone`)
get_device() {
    h_status=$(amixer contents | grep "Headphone Jack" -A 2 | tail -n 1 | cut -d "=" -f2)
    device="Speaker"
    if [[ $h_status = "on" ]]; then
        device="Headphone"
    fi
}

# Get the status of the active device (ie. `on` or `off`)
get_device_status() {
    device_status=$(amixer get $device | tail -n 1 | cut -d "[" -f4 | cut -d "]" -f1)
}

# Get the volume of the active device as a percentage (eg. 10)
get_volume() {
    volume=$(amixer get $device | tail -n 1 | grep -o "\[.*%\]" | sed "s/[^0-9]//g")
}

# Get the icon to display in the notifications for the active device
get_icon() {
    get_device_status
    if [[ $device_status == "off" || $volume -lt 1 ]]; then
        icon_name=$ICON_VOL0
    elif [[ $volume -lt 33 ]]; then
        icon_name=$ICON_VOL1
    elif [[ $volume -lt 66 ]]; then
        icon_name=$ICON_VOL2
    else
        icon_name=$ICON_VOL3
    fi
}

notify() {
    get_volume
    get_icon
    dunstify -a volume-controller -u low -r 9993 -h int:value:$volume -i $icon_name -t 1000 "Volume: $volume% ($device)"
}

# Set the volume of the individual devices to max
initialise() {
    amixer set Master 100% on
    # amixer set Headphone 100%
    # amixer set Speaker 100%
}

# Increase the master volume
increase() {
    amixer set $device 1%+ on
}

# Decrease the master volume
decrease() {
    amixer set $device 1%- on
}

initialise
get_device
if [[ $1 = "inc" ]]; then
    increase
    notify
elif [[ $1 = "dec" ]]; then
    decrease
    notify
elif [[ $1 = "mute" ]]; then
    amixer set $device 0+ toggle
    get_icon
    notify
elif [[ $1 = "get" ]]; then
    get_volume
    echo $volume
else
    echo "UNKNOWN COMMAND"
    exit 1
fi
